/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Pty {
  fd: number
  pid: number
  constructor(command: string, args: Array<string>, envs: Record<string, string>, dir: string, size: [cols: number, rows: number], onExit: (err: null | Error, exitCode: number) => void)
  resize(size: [cols: number, rows: number]): void
}
