/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Size {
  cols: number;
  rows: number;
}
export class Pty {
  fd: number;
  pid: number;
  constructor(
    command: string,
    args: Array<string>,
    envs: Record<string, string>,
    dir: string,
    size: Size,
    onExit: (err: null | Error, exitCode: number) => void,
  );
  resize(size: Size): void;
}
